services:   
  newsbot:   
    build: .   
    depends_on:   
      - mysql   
    restart: "on-failure"   
    env_file:  
      - token.env 
    networks: 
      - newsbot 

  mysql:   
    image: mysql:8  
    volumes:   
        - newsbot-db:/var/lib/mysql   
    env_file:
      - mysql.env        
    networks: 
      - newsbot 

  adminer: 
    image: adminer 
    ports: 
        - 8080:8080
    networks:
      - newsbot

volumes:   
  newsbot-db:  


networks: 
  newsbot: 